### ISSUE TITLE
extra_setup dictionary lost for composite functions

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#113] opened 2020-03-06 03:38 UTC
Certain functions have properties that cannot be expressed as numeric parameters, e.g. the particle distribution of a synchrotron spectrum. These extra properties are saved to a special dictionary, `extra_setup`, during pickling etc., so they can be parsed back again later. This does not seem to work for composite functions, see example below (needs `naima`). This means that models containing composite functions relying on `extra_setup` cannot be properly copied, saved to and loaded from yml files, or saved to a fits file as part of threeML.analysis_results etc.

```
from threeML import *

syn1 = Synchrotron()
syn2 = Synchrotron()

spectrum1 = syn1
source1 = PointSource("source1", 80, 20, spectrum1)
syn1.set_particle_distribution( Powerlaw() )

spectrum2 = syn2*Constant()
source2 = PointSource("source2", 80, 20, spectrum2)
syn2.set_particle_distribution( Powerlaw() )

model = Model( source1, source2 )
  
print "source1 has extra_setup:", "extra_setup" in repr(model.to_dict()["source1"]), \
model.to_dict()["source1"]["spectrum"]["main"]["Synchrotron"]["extra_setup"]
print "source2 has extra_setup:", "extra_setup" in repr(model.to_dict()["source2"])  
```

Output:

```
source1 has extra_setup: True {'particle_distribution': 'Powerlaw'}
source2 has extra_setup: False
```

**Comment by grburgess** [comment] 2020-05-01 05:30
Perhaps we can all have a meeting on this to discuss the best way to handle this as it seems to be a recurring issue @henrikef ?

**Comment by henrikef** [comment] 2021-05-28 17:44
Sounds cleaner than the current thing with `extra_setup`. How much effort would that be?

**Comment by grburgess** [comment] 2021-05-28 19:04
I've nearly got it down. There is no effort on the user side except if you want to make complicated functions.

**Comment by grburgess** [comment] 2021-05-29 10:28
Ok. So instead of adding children to the function which would have complicated things. I've now allowed functions to have links to external functions. For example, the synchrotron functions has an electron spectrum that could be in a particle source. We do not want to add that function as a child to the synchrotron because then the function would have two parents. Rather, we can add some syntax magic to make the function remember that it was linked in the same way that we link parameters:

```python

       def set_particle_distribution(self, function):

            if "particle_distribution" in self._external_functions:

                self.unlink_external_function("particle_distribution")

            self.link_external_function(function, "particle_distribution")

            self._particle_distribution_name = function.name

            self._particle_distribution = function


            # Now set the units for the function

```

and this functionality can be general rather than just existing for synchrotron. 

Since the extra_setups thing was never had a specific design, it is hard to predict what it will do, thus, this change will tackle a specific, but widely applicable problem with a well defined interface for the user. 


```python
    def link_external_function(self, function: "Function", internal_name: str ):

        if not isinstance(function, Function):

            log.error("external functions must be of type Function")

            raise RuntimeError()

        if internal_name in self._external_functions:

            log.error(f"a function with internal name {internal_name} is already linked!")

            raise RuntimeError()


        self._external_functions[internal_name] = function

        log.debug(f"{self.name} has now linked {function.name} as {internal_name}")

    def unlink_external_function(self, internal_name: str):

        """
        unlink an external function

        :param internal_name: 
        :type internal_name: str
        :returns: 

        """
        if internal_name not in self._external_functions:

            log.error(f"{internal_name} is not linked.")
            log.error(f"Have {','.join(list(self._external_functions.keys()))}")
        
            raise RuntimeError()

        self._external_functions.pop(internal_name)

```

Its currently branched off the new node type. But since it is a major change to the parser, etc, I'm fine waiting for that to be merged first. 

Also, the parser can load and reload functions with linked functions even if they are composite.

**Comment by grburgess** [comment] 2021-05-30 13:01
The issue is now solved in a branch off of native node. There is no change to the outward interface for the synchrotron function, but we now have an easier user interface for building these types of functions.

**Comment by henrikef** [comment] 2021-06-01 22:05
Ok, great! What about cases where the extra data is a string and not another node in the model? For example, [SpatialTemplate_2D](https://github.com/threeML/astromodels/blob/master/astromodels/functions/functions_2D.py#L598) or [EBLAttenuation](https://github.com/threeML/astromodels/blob/master/astromodels/functions/functions_1D/functions.py#L788) (currently not implemented, but the extra data would be a string referring to the EBL model name).

**Comment by grburgess** [comment] 2021-06-02 04:32
@henrikef I've been thinking about this some more. There was a solution offered in that issue to have multiple classes. it's likely we could adapt the extra setups as well to just handle files. OR we could add an astromodels configuration and have these set there which would mean that we do not have to store the information in the class, but the user would have to remember what they used. I'm not sure what is best solution.

**Comment by henrikef** [comment] 2021-06-02 17:24
So the extra_setup works (or used to work) for strings/filenames etc, it's not ideal though (I kind of hacked the parser, it's not very elegant). This is fine for `SpatialTemplate_2D` since that's usually used by itself.

The problem is that the entire dictionary is lost during pickling/unpickling of composite functions. E.g. if I have a `Powerlaw() * EBLattenuation()`, the dictionary wouldn't get picked up during parsing. Since `EBLattenuation` is only used in composite functions, I never bothered to add the dictionary there (since it wouldn't survive copying etc).

Not storing the information with the function is a little risky. E.g. the TS calculation relies on copying the model, and the user has no way to reset anything at that point. Also, you might have multiple `SpatialTemplate_2D` instances in the same model etc.

**Comment by grburgess** [comment] 2021-06-03 13:27
@henrikef  Ok, I found another solution to fix this that also expands the ability of the model. 

I've added the ability to have "properties" as well as parameters to functions. These are specified in the yaml doc string like parameters but they take on str values:

```python
class _ComplexTestFunction(Function1D, metaclass=FunctionMeta):
    r"""
    description :
        A useless function to be used during automatic tests

    latex: not available

    parameters :
        A :
            desc : none
            initial value : 3.24e-6
            min : 1e-6
            max : 1e-5

        B :
            desc : none
            initial value : -10
            min : -100
            max : 100
            delta : 0.1
    
    properties:
        file_name: 
            desc: a file name
            defer: True 
        dummy:
            desc: a dummy property
            initial value: test
            allowed values:
                - test
                - love

    """


```

These have some special properties. 

1) The initial value can be deferred to instantiation if you need to specify a a file name at runtime. It will crash if a deferred property is not passed to the class. 

2) The values can be limited to a list for example the EBL model names. 

Properties are like parameters except that they are not needed in the function call and thus they are saved along with their current values to the model dictionary. This works for composites as well. This also means that adding an manipulating the values works just like a parameter so we do not need to have extra magic like extra_setups for the user to build complex functions. Everything happens behind the scenes.

This is built off the new node class and will be merged into production after that.

**Comment by henrikef** [comment] 2021-06-04 00:50
Ohh, I like it! This is much nicer than the extra_setup stuff. I'll try to play around with this soon, I think this will be nice also for wrappers for other naima functions. Btw, do the parameters have to be strings or could they also be more general pickle-able python objects? I'm thinking about the [inverse Compton](https://naima.readthedocs.io/en/latest/radiative.html) model, which takes a list of seed photon fields as parameter where each photon field can be specified in different ways. But anyway, I'll try it out.

**Closed** 2021-07-19 02:10 UTC
Labels: bug, no-issue-activity
