### ISSUE TITLE
Xsect data not downloaded when installing with pip

### ISSUE THREAD

**Issue by domeckert** [threeML/astromodels#152] opened 2021-05-12 04:19 UTC
Hi everyone, 

I upgraded my install of 3ml/astromodels with pip and found out when trying to load the PhAbs model that the cross section data was inaccessible. The corresponding folder was absent. 

I believe this can be fixed easily by adding the data/xsect directory to MANIFEST.in

Cheers 
Dominique

**Comment by grburgess** [comment] 2021-05-12 08:35
@domeckert I see what the issue is. Will fix this afternoon.

**Comment by grburgess** [comment] 2021-05-13 09:43
@domeckert this should be fixed now, but will need to wait until the next release before it is up on pypi

**Closed** 2021-07-15 02:09 UTC
Labels: bug, no-issue-activity
